# Generated by Django 5.1.2 on 2025-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('invoice_pono', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_podate', models.DateField(blank=True, null=True)),
                ('customer_phone', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_gst', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('customer_pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('vehicle_model', models.CharField(max_length=255)),
                ('vehicle_make', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_license_plate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_external_bikeid', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_registration_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_year_of_manufacture', models.DateField(blank=True, null=True)),
                ('vehicle_fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_transmission_type', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_engine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_chassis_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_vin_no', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_reg_state', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_reg_exp', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('final_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bulkuploadinvoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
