# Generated by Django 5.1.2 on 2025-07-07 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0002_bulkuploadinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadinvoices',
            name='final_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='bulkuploadinvoices',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='BulkUploadInvoiceParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_source', models.CharField(choices=[('inventory', 'Inventory'), ('external', 'External')], max_length=20)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('part_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('part_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('part_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkuploadinvoiceparts', to='GMSApp.bulkuploadinvoices')),
            ],
            options={
                'db_table': 'bulkuploadinvoiceparts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadInvoiceServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_source', models.CharField(choices=[('service', 'Service'), ('external', 'External')], max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('service_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulkuploadinvoiceservices', to='GMSApp.bulkuploadinvoices')),
            ],
            options={
                'db_table': 'bulkuploadinvoiceservices',
                'ordering': ['-created_at'],
            },
        ),
    ]
