# Generated by Django 5.1.2 on 2025-07-07 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0003_alter_bulkuploadinvoices_final_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackInvoiceUploads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, unique=True)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0, help_text='Total number of records (success + failed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'track_invoice_uploads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bulkuploadinvoices',
            name='track_invoice_uploads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_upload_invoices', to='GMSApp.trackinvoiceuploads'),
        ),
    ]
