# Generated by Django 5.1.2 on 2025-07-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0004_trackinvoiceuploads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadinvoiceparts',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='bulkuploadinvoices',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AlterField(
            model_name='bulkuploadinvoiceservices',
            name='status',
            field=models.TextField(default='pending'),
        ),
    ]
