# Generated by Django 5.1.2 on 2025-07-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0005_alter_bulkuploadinvoiceparts_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadinvoices',
            name='final_status',
            field=models.TextField(default='pending'),
        ),
    ]
