# Generated by Django 5.1.2 on 2025-07-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0006_alter_bulkuploadinvoices_final_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txnservice',
            name='service_type',
        ),
        migrations.DeleteModel(
            name='TXNServicetype',
        ),
    ]
