# Generated by Django 5.1.2 on 2025-07-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0007_remove_txnservice_service_type_delete_txnservicetype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelGarageTXNservice',
        ),
    ]
