# Generated by Django 5.1.2 on 2025-07-14 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0008_delete_relgaragetxnservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinvoiceuploads',
            name='garage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='track_invoice_uploads', to='GMSApp.garage'),
            preserve_default=False,
        ),
    ]
