# Generated by Django 5.1.2 on 2025-07-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0009_trackinvoiceuploads_garage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='trackinvoiceuploads',
            table='invoice_bulk_uploads',
        ),
    ]
