# Generated by Django 5.1.2 on 2025-07-14 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0010_alter_trackinvoiceuploads_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBulkUploadTXN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True)),
                ('status', models.TextField(default='pending')),
                ('final_status', models.TextField(default='pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bulk_upload_txn', to='GMSApp.customer')),
                ('track_invoice_uploads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bulk_upload_txn', to='GMSApp.trackinvoiceuploads')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bulk_upload_txn', to='GMSApp.vehicle')),
            ],
            options={
                'db_table': 'invoice_bulk_upload_txn',
                'ordering': ['-created_at'],
            },
        ),
    ]
