# Generated by Django 5.1.2 on 2025-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0011_invoicebulkuploadtxn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinvoiceuploads',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='trackinvoiceuploads',
            unique_together={('garage', 'file_name')},
        ),
    ]
