# Generated by Django 5.1.2 on 2025-07-14 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0012_alter_trackinvoiceuploads_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinvoiceuploads',
            name='garage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bulk_uploads', to='GMSApp.garage'),
        ),
    ]
