# Generated by Django 5.1.2 on 2025-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0013_alter_trackinvoiceuploads_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackinvoiceuploads',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
