# Generated by Django 5.1.2 on 2025-07-15 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0014_trackinvoiceuploads_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkuploadinvoices',
            name='track_invoice_uploads',
        ),
        migrations.RemoveField(
            model_name='bulkuploadinvoiceservices',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='BulkUploadInvoiceParts',
        ),
        migrations.DeleteModel(
            name='BulkUploadInvoices',
        ),
        migrations.DeleteModel(
            name='BulkUploadInvoiceServices',
        ),
    ]
