# Generated by Django 5.1.2 on 2025-07-15 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0015_remove_bulkuploadinvoices_track_invoice_uploads_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='txnservice',
            table='invoice_service',
        ),
    ]
