# Generated by Django 5.1.2 on 2025-07-18 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0016_alter_txnservice_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Garage rating from 0.0 to 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='subscriberbookingreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, help_text='SubscriberBookingReview rating from 0.0 to 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
