# Generated by Django 5.1.2 on 2025-07-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0017_garage_rating_alter_subscriberbookingreview_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhar', models.CharField(max_length=20)),
                ('attachment', models.CharField(max_length=255)),
                ('role', models.JSONField(help_text="List of roles, e.g. ['crew'] or ['mechanic'] or ['crew', 'mechanic']")),
                ('reference_by_name', models.CharField(max_length=255)),
                ('reference_by_phone', models.CharField(max_length=15)),
                ('reference_by_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('year_of_experience', models.PositiveIntegerField()),
                ('past_experience', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_staff', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'garage_staff',
                'ordering': ['-created_at'],
                'unique_together': {('phone', 'garage')},
            },
        ),
    ]
