# Generated by Django 5.1.2 on 2025-07-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0018_garagestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtimeline',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
