# Generated by Django 5.1.2 on 2025-07-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0019_bookingtimeline_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_checklist', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'service_checklist',
                'ordering': ['-created_at'],
                'unique_together': {('garage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_accessories', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'vehicle_accessories',
                'ordering': ['-created_at'],
                'unique_together': {('garage', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VehicleCommonIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_common_issues', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'vehicle_common_issues',
                'ordering': ['-created_at'],
                'unique_together': {('garage', 'name')},
            },
        ),
    ]
