# Generated by Django 5.1.2 on 2025-07-28 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0020_servicechecklist_vehicleaccessories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehiclenumber', models.CharField(max_length=100)),
                ('vehicletype', models.CharField(max_length=100)),
                ('currentreading', models.FloatField(default=0)),
                ('odometerreading', models.FloatField(default=0)),
                ('vehicleotherissues', models.TextField(blank=True, null=True)),
                ('customername', models.CharField(max_length=255)),
                ('customermobile', models.CharField(max_length=15)),
                ('customercomments', models.TextField(blank=True, null=True)),
                ('customertype', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], editable=False, max_length=20)),
                ('damagedescription', models.TextField(blank=True, null=True)),
                ('damagephotos', models.JSONField(blank=True, default=list)),
                ('fuelpercentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('serviceremarks', models.TextField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.subscriberbooking')),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.garage')),
                ('vehiclebrand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GMSApp.brand')),
                ('vehiclemodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GMSApp.model')),
            ],
            options={
                'db_table': 'jobcard',
                'ordering': ['-created_at'],
                'unique_together': {('garage', 'vehiclenumber', 'customermobile', 'customertype')},
            },
        ),
        migrations.CreateModel(
            name='JobcardServiceChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_service_checklist', to='GMSApp.jobcard')),
                ('servicechecklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_service_checklist', to='GMSApp.servicechecklist')),
            ],
            options={
                'db_table': 'jobcard_service_checklist',
                'ordering': ['-created_at'],
                'unique_together': {('jobcard', 'servicechecklist')},
            },
        ),
        migrations.CreateModel(
            name='JobcardVehicleAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_accessories', to='GMSApp.jobcard')),
                ('vehicleaccessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_accessories', to='GMSApp.vehicleaccessories')),
            ],
            options={
                'db_table': 'jobcard_vehicle_accessories',
                'ordering': ['-created_at'],
                'unique_together': {('jobcard', 'vehicleaccessories')},
            },
        ),
        migrations.CreateModel(
            name='JobcardVehicleCommonIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_common_issues', to='GMSApp.jobcard')),
                ('vehiclecommonissues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_common_issues', to='GMSApp.vehiclecommonissues')),
            ],
            options={
                'db_table': 'jobcard_vehicle_common_issues',
                'ordering': ['-created_at'],
                'unique_together': {('jobcard', 'vehiclecommonissues')},
            },
        ),
    ]
