# Generated by Django 5.1.2 on 2025-07-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0021_jobcard_jobcardservicechecklist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='currentreading',
            new_name='dailyrunning',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='serviceremarks',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicleotherissues',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='diagram_image',
            field=models.CharField(blank=True, help_text='Path to the vehicle diagram image with dent markings', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('finalized', 'Finalized')], default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicleage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehiclemileage',
            field=models.FloatField(default=0),
        ),
    ]
