# Generated by Django 5.1.2 on 2025-08-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0022_rename_currentreading_jobcard_dailyrunning_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicechecklist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleaccessories',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecommonissues',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehiclefueltype',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('ev', 'EV')], default='petrol', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicechecklist',
            name='vehicletype',
            field=models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicleaccessories',
            name='vehicletype',
            field=models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecommonissues',
            name='vehicletype',
            field=models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='vehicletype',
            field=models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='servicechecklist',
            unique_together={('garage', 'name', 'vehicletype')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicleaccessories',
            unique_together={('garage', 'name', 'vehicletype')},
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecommonissues',
            unique_together={('garage', 'name', 'vehicletype')},
        ),
    ]
