# Generated by Django 5.1.2 on 2025-08-07 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0023_alter_servicechecklist_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobcardBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_brands', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'jobcard_brands',
                'ordering': ['-created_at'],
                'unique_together': {('garage', 'name', 'vehicletype')},
            },
        ),
        migrations.CreateModel(
            name='JobcardModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('displayname', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_models', to='GMSApp.garage')),
                ('jobcardbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_models', to='GMSApp.jobcardbrands')),
            ],
            options={
                'db_table': 'jobcard_models',
                'ordering': ['-created_at'],
                'unique_together': {('garage', 'jobcardbrand', 'name', 'vehicletype')},
            },
        ),
    ]
