# Generated by Django 5.1.2 on 2025-08-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0024_jobcardbrands_jobcardmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclebrand',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclemodel',
        ),
    ]
