# Generated by Django 5.1.2 on 2025-08-07 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0025_remove_jobcard_vehiclebrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehiclebrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GMSApp.jobcardbrands'),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehiclemodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GMSApp.jobcardmodels'),
        ),
    ]
