# Generated by Django 5.1.2 on 2025-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0026_jobcard_vehiclebrand_jobcard_vehiclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='dent_positions',
            field=models.JSONField(blank=True, default=list, help_text='Stores the coordinates and details of dents on the vehicle', null=True),
        ),
    ]
