# Generated by Django 5.1.2 on 2025-08-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0027_jobcard_dent_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='dent_positions',
        ),
        migrations.AddField(
            model_name='subscriberbooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriberbooking', to='GMSApp.customer'),
        ),
        migrations.AddField(
            model_name='subscriberbooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriberbooking', to='GMSApp.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='jobcardbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='GMSApp.jobcardbrands'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='jobcardmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='GMSApp.jobcardmodels'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicletype',
            field=models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], default='2', max_length=100),
        ),
    ]
