# Generated by Django 5.1.2 on 2025-08-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0028_remove_jobcard_dent_positions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='customertype',
            new_name='mode',
        ),
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together={('garage', 'vehiclenumber', 'mode')},
        ),
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.customer'),
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customercomments',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customermobile',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='customername',
        ),
    ]
