# Generated by Django 5.1.2 on 2025-08-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0029_rename_customertype_jobcard_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together={('garage', 'customer', 'mode')},
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='dailyrunning',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='fuelpercentage',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='odometerreading',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicleage',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclebrand',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclefueltype',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclemileage',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclemodel',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehiclenumber',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='vehicletype',
        ),
    ]
