# Generated by Django 5.1.2 on 2025-08-19 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0030_alter_jobcard_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.vehicle'),
        ),
    ]
