# Generated by Django 5.1.2 on 2025-08-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0031_jobcard_vehicle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together={('garage', 'customer', 'vehicle', 'mode')},
        ),
    ]
