# Generated by Django 5.1.2 on 2025-08-19 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0032_alter_jobcard_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='dailyrunning',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuelpercentage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometerreading',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicleage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehiclemileage',
            field=models.FloatField(default=0),
        ),
    ]
