# Generated by Django 5.1.2 on 2025-08-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0033_vehicle_dailyrunning_vehicle_fuelpercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.estimate'),
        ),
    ]
