# Generated by Django 5.1.2 on 2025-08-21 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0034_jobcard_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.invoice'),
        ),
    ]
