# Generated by Django 5.1.2 on 2025-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0035_jobcard_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
