# Generated by Django 5.2.4 on 2025-09-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0036_estimate_comments_invoice_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='jobcard_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='jobtype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
