# Generated by Django 5.1.2 on 2025-09-18 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0038_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobcardCustomerVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_voice', models.CharField(max_length=200)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_customervoice', to='GMSApp.jobcard')),
            ],
            options={
                'db_table': 'jobcard_customervoice',
            },
        ),
    ]
