# Generated by Django 5.1.2 on 2025-09-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0039_jobcardcustomervoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='fuel_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='km_reading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
