# Generated by Django 5.1.2 on 2025-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0040_jobcard_fuel_level_jobcard_km_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='customer_voice',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
