# Generated by Django 5.1.2 on 2025-09-18 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0041_jobcard_customer_voice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobcardCustomerVoice',
        ),
    ]
