# Generated by Django 5.1.2 on 2025-09-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0042_delete_jobcardcustomervoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagestaff',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
