# Generated by Django 5.1.2 on 2025-09-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0043_alter_garagestaff_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobcard_Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('garage_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_garage_staff', to='GMSApp.garagestaff')),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_assigned_staff', to='GMSApp.jobcard')),
            ],
            options={
                'db_table': 'jobcard_assigned',
            },
        ),
    ]
