# Generated by Django 5.1.2 on 2025-09-20 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0044_jobcard_assigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobcardParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=255)),
                ('part_source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('part_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('part_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('part_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_parts', to='GMSApp.productcatalogues')),
            ],
            options={
                'db_table': 'jobcard_parts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobcardServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=255)),
                ('service_source', models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], max_length=20)),
                ('service_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('service_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('service_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_services', to='GMSApp.txnservice')),
            ],
            options={
                'db_table': 'jobcard_services',
                'ordering': ['-created_at'],
            },
        ),
    ]
