# Generated by Django 5.1.2 on 2025-09-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0045_jobcardparts_jobcardservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobType',
        ),
    ]
