# Generated by Django 5.1.2 on 2025-09-25 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0046_delete_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobtype', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'jobtype',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'garage', 'vehicletype')},
            },
        ),
    ]
