# Generated by Django 5.1.2 on 2025-09-25 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0047_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='jobtype',
        ),
    ]
