# Generated by Django 5.1.2 on 2025-09-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0048_remove_jobcard_jobtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='jobtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.jobtype'),
        ),
    ]
