# Generated by Django 5.1.2 on 2025-09-26 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0049_jobcard_jobtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='customer_voice',
        ),
    ]
