# Generated by Django 5.1.2 on 2025-09-26 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0050_remove_jobcard_customer_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.garagestaff'),
        ),
    ]
