# Generated by Django 5.1.2 on 2025-09-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0051_jobcard_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardparts',
            name='jobcard_number',
        ),
        migrations.RemoveField(
            model_name='jobcardservices',
            name='jobcard_number',
        ),
    ]
