# Generated by Django 5.1.2 on 2025-09-29 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0052_remove_jobcardparts_jobcard_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardparts',
            name='jobcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_parts', to='GMSApp.jobcard'),
        ),
        migrations.AddField(
            model_name='jobcardservices',
            name='jobcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_services', to='GMSApp.jobcard'),
        ),
    ]
