# Generated by Django 5.1.2 on 2025-09-29 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0053_jobcardparts_jobcard_jobcardservices_jobcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobcardCustomerVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_voice', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_customer_voice', to='GMSApp.jobcard')),
            ],
            options={
                'db_table': 'jobcard_customer_voice',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobcardMechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_mechanic', to='GMSApp.jobcard')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_mechanic', to='GMSApp.garagestaff')),
            ],
            options={
                'db_table': 'jobcard_mechanic',
                'ordering': ['-updated_at'],
            },
        ),
    ]
