# Generated by Django 5.1.2 on 2025-09-30 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0054_jobcardcustomervoice_jobcardmechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_issue_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GarageVehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_issue', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicle_issue', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'garage_vehicle_issue',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobcardVehicleIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_issue', to='GMSApp.jobcard')),
                ('vehicleissue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_issue', to='GMSApp.garagevehicleissue')),
            ],
            options={
                'db_table': 'jobcard_vehicle_issue',
                'ordering': ['-updated_at'],
            },
        ),
    ]
