# Generated by Django 5.1.2 on 2025-09-30 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0055_jobcard_vehicle_issue_description_garagevehicleissue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarageVehicleAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_accessory', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicle_accessory', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'garage_vehicle_accessory',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GarageVehicleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_damage', models.CharField(max_length=255)),
                ('vehicletype', models.CharField(choices=[('2', '2 Wheeler'), ('3', '3 Wheeler'), ('4', '4 Wheeler'), ('6', '6 Wheeler')], max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garage_vehicle_damage', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'garage_vehicle_damage',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobcardVehicleAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_accessory', to='GMSApp.jobcard')),
                ('vehicleaccessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_accessory', to='GMSApp.garagevehicleaccessory')),
            ],
            options={
                'db_table': 'jobcard_vehicle_accessory',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobcardVehicleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_damage', to='GMSApp.jobcard')),
                ('vehicledamage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobcard_vehicle_damage', to='GMSApp.garagevehicledamage')),
            ],
            options={
                'db_table': 'jobcard_vehicle_damage',
                'ordering': ['-updated_at'],
            },
        ),
    ]
