# Generated by Django 5.1.2 on 2025-09-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0056_garagevehicleaccessory_garagevehicledamage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_accessory_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_damage_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
