# Generated by Django 5.1.2 on 2025-09-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0057_jobcard_vehicle_accessory_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='damagedescription',
        ),
    ]
