# Generated by Django 5.1.2 on 2025-10-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0058_remove_jobcard_damagedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
