# Generated by Django 5.1.2 on 2025-10-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0059_customer_alt_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='vehicle_type',
            field=models.CharField(default='2', max_length=20),
        ),
    ]
