# Generated by Django 5.1.2 on 2025-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0060_jobcard_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='deliverable_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='reminder_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='reminder_km',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='work_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
