# Generated by Django 5.1.2 on 2025-10-09 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0062_jobcardpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobcard', to='GMSApp.users'),
        ),
    ]
