# Generated by Django 5.1.2 on 2025-10-14 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0063_jobcard_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='random_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
