# Generated by Django 5.1.2 on 2025-10-16 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0064_jobcard_random_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcatalogues',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_catalogues', to='GMSApp.productbrands'),
        ),
    ]
