# Generated by Django 5.1.2 on 2025-10-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0065_alter_productcatalogues_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriberbooking',
            old_name='payment_id',
            new_name='jobcard_id',
        ),
        migrations.RemoveField(
            model_name='model',
            name='business',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='business',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='subscriberbooking',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='subscribervehicle',
            name='business',
        ),
        migrations.AddField(
            model_name='model',
            name='vehicletype',
            field=models.CharField(default='2', max_length=255),
        ),
    ]
