# Generated by Django 5.1.2 on 2025-10-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0066_rename_payment_id_subscriberbooking_jobcard_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
