# Generated by Django 5.1.2 on 2025-10-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0067_delete_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookingstatus',
            table='subscriberbookingstatus',
        ),
        migrations.AlterModelTable(
            name='bookingtimeline',
            table='subscriberbookingtimeline',
        ),
    ]
