# Generated by Django 5.1.2 on 2025-10-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0068_alter_bookingstatus_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobcardvehicleaccessories',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobcardvehicleaccessories',
            name='jobcard',
        ),
        migrations.RemoveField(
            model_name='jobcardvehicleaccessories',
            name='vehicleaccessories',
        ),
        migrations.AlterUniqueTogether(
            name='jobcardvehiclecommonissues',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='jobcardvehiclecommonissues',
            name='jobcard',
        ),
        migrations.RemoveField(
            model_name='jobcardvehiclecommonissues',
            name='vehiclecommonissues',
        ),
        migrations.AlterUniqueTogether(
            name='servicechecklist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicechecklist',
            name='garage',
        ),
        migrations.AlterUniqueTogether(
            name='vehicleaccessories',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vehicleaccessories',
            name='garage',
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecommonissues',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vehiclecommonissues',
            name='garage',
        ),
        migrations.DeleteModel(
            name='JobcardServiceChecklist',
        ),
        migrations.DeleteModel(
            name='JobcardVehicleAccessories',
        ),
        migrations.DeleteModel(
            name='JobcardVehicleCommonIssues',
        ),
        migrations.DeleteModel(
            name='ServiceChecklist',
        ),
        migrations.DeleteModel(
            name='VehicleAccessories',
        ),
        migrations.DeleteModel(
            name='VehicleCommonIssues',
        ),
    ]
