# Generated by Django 5.1.2 on 2025-10-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0070_remove_amctype_business_remove_amctype_garage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business_feature',
        ),
    ]
