# Generated by Django 5.1.2 on 2025-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0071_delete_business_feature'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='customer',
        #     unique_together={('garage', 'phone')},
        # ),
    ]
