# Generated by Django 5.1.2 on 2025-10-24 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0072_alter_customer_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesspermissions',
            name='business',
        ),
    ]
