# Generated by Django 5.1.2 on 2025-10-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0073_remove_businesspermissions_business'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Business',
        # ),
        migrations.RemoveField(
            model_name='jobcard',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='invoice',
        ),
    ]
