# Generated by Django 5.1.2 on 2025-10-27 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0074_delete_business_remove_jobcard_estimate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='deliverable_datetime',
            new_name='delivery_timeline',
        ),
    ]
