# Generated by Django 5.1.2 on 2025-10-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0076_alter_vehicle_year_of_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
