# Generated by Django 5.2.4 on 2025-10-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0077_alter_vehicle_year_of_manufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
