# Generated by Django 5.2.8 on 2025-11-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0078_alter_vehicle_year_of_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberbooking',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriberbooking', to='GMSApp.customer'),
        ),
    ]
