# Generated by Django 5.2.8 on 2025-11-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0079_delete_business_subscriberbooking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriberbooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriberbooking', to='GMSApp.vehicle'),
        )
    ]
