# Generated by Django 5.2.8 on 2025-12-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0080_delete_business_subscriberbooking_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobcard',
            unique_together=set(),
        )
    ]
