# Generated by Django 5.2.8 on 2025-12-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0081_delete_business_alter_jobcard_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelGarageVehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_garage_vehicletype', to='GMSApp.garage')),
            ],
            options={
                'db_table': 'rel_garage_vehicletype',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_ev', models.BooleanField(default=False)),
                ('wheeler', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicle_type',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='relgaragevehicletype',
            name='vehicletype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_garage_vehicletype', to='GMSApp.vehicletype'),
        ),
        migrations.AlterUniqueTogether(
            name='relgaragevehicletype',
            unique_together={('garage', 'vehicletype')},
        ),
    ]
