# Generated by Django 5.2.8 on 2025-12-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0083_productcatalogues_min_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('garage', 'phone')},
        ),
    ]
