# Generated by Django 5.2.8 on 2025-12-14 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0084_delete_business_alter_customer_unique_together'),
        ('GMSApp', '0084_productcatalogues_price_includes_gst'),
    ]

    operations = [
    ]
