# Generated by Django 5.2.8 on 2025-12-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0085_merge_20251214_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardparts',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcardparts',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcardservices',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
