# Generated by Django 5.2.8 on 2025-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GMSApp', '0086_jobcardparts_code_jobcardparts_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinwards',
            name='price_includes_gst',
            field=models.BooleanField(default=False, help_text='Whether the rate includes GST'),
        ),
    ]
